-- Auto-generated by DMS - do not edit manually

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic-Gruvbox")
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic-Gruvbox")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_SIZE", "24")
