-- Auto-generated by DMS - do not edit manually

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "desc:AU Optronics 0x21ED",
    mode = "1920x1080@60.056",
    position = "0x0",
    scale = "1.5",
})

