sub-ass-override=force
sub-color='#FFFF00'
sub-border-size=2
osc=no
keep-open=yes
force-window=yes
image-display-duration=inf
cursor-autohide=1000
screenshot-format=png
ytdl-raw-options=cookies=/home/ann/ytdlp.txt
