-- Hyprland Configuration
-- https://wiki.hypr.land/Configuring/

-- ==================
-- MONITOR CONFIG
-- ==================
-- Monitors from existing configuration
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080",
    position = "0x0",
    scale = "1",
    bitdepth = 10,
    cm = "hdr",
})

-- ==================
-- STARTUP APPS
-- ==================

-- env vars
--env = DMS_DISABLE_MATUGEN, 1
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("XDG_MENU_PREFIX", "arch-")

-- ==================
-- INPUT CONFIG
-- ==================

hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 3,
    bezier = "default",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 3,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5,
    bezier = "default",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 4,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 3,
    bezier = "default",
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

hl.window_rule({
    name = "windowrule-1",
    match = {
        class = "^(org\\.wezfurlong\\.wezterm)$",
    },
    float = false,
    border_size = 0,
})

hl.window_rule({
    name = "windowrule-2",
    match = {
        class = "^(org\\.gnome\\.)",
    },
    rounding = 12,
    border_size = 0,
})

hl.window_rule({
    name = "windowrule-3",
    match = {
        class = "^(gnome-control-center)$",
    },
    float = false,
})

hl.window_rule({
    name = "windowrule-4",
    match = {
        class = "^(pavucontrol)$",
    },
    float = false,
})

hl.window_rule({
    name = "windowrule-5",
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = false,
})

hl.window_rule({
    name = "windowrule-6",
    match = {
        class = "^(gnome-calculator)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-7",
    match = {
        class = "^(galculator)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-8",
    match = {
        class = "^(blueman-manager)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-9",
    match = {
        class = "^(steam)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-10",
    match = {
        class = "^(xdg-desktop-portal)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-11",
    match = {
        class = "^(Alacritty)$",
    },
    border_size = 0,
})

hl.window_rule({
    name = "windowrule-12",
    match = {
        class = "^(zen)$",
    },
    border_size = 0,
})

hl.window_rule({
    name = "windowrule-13",
    match = {
        class = "^(com\\.mitchellh\\.ghostty)$",
    },
    border_size = 0,
})

hl.window_rule({
    name = "windowrule-14",
    match = {
        class = "^(kitty)$",
    },
    border_size = 0,
})

hl.window_rule({
    name = "windowrule-15",
    match = {
        class = "^(firefox)$",
        title = "^(Picture-in-Picture)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-16",
    match = {
        class = "^(zoom)$",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-17",
    match = {
        class = "^(helium)$",
    },
    border_size = 0,
    no_shadow = true,
})

hl.window_rule({
    name = "windowrule-1",
    match = {
        class = "^(org.quickshell)$",
    },
    float = true,
})

local mod = "SUPER"

hl.bind(mod .. " + T", hl.dsp.exec_cmd("kitty"))
hl.bind(mod .. " + Return", hl.dsp.exec_cmd("kitty tmux new-session -A -s main"))
hl.bind(mod .. " + A", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
hl.bind(mod .. " + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"))
hl.bind(mod .. " + P", hl.dsp.exec_cmd("dms ipc call powermenu toggle"))
hl.bind(mod .. " + M", hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"))
hl.bind(mod .. " + comma", hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"))
hl.bind(mod .. " + N", hl.dsp.exec_cmd("dms ipc call notifications toggle"))
hl.bind(mod .. " + SHIFT + N", hl.dsp.exec_cmd("dms ipc call notepad toggle"))
hl.bind(mod .. " + Y", hl.dsp.exec_cmd("dms ipc call dankdash wallpaper"))
hl.bind(mod .. " + TAB", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))

hl.bind(mod .. " + B", hl.dsp.exec_cmd("zen-browser"))
hl.bind(mod .. " + H", hl.dsp.exec_cmd("helium-browser"))
hl.bind(mod .. " + E", hl.dsp.exec_cmd("dolphin"))

hl.bind(mod .. " + period", hl.dsp.layout("move +col"))
hl.bind(mod .. " + comma", hl.dsp.layout("move -col"))
hl.bind(mod .. " + SHIFT + period", hl.dsp.layout("movewindowto r"))
hl.bind(mod .. " + SHIFT + comma", hl.dsp.layout("movewindowto l"))
hl.bind(mod .. " + SHIFT + up", hl.dsp.layout("movewindowto u"))
hl.bind(mod .. " + SHIFT + down", hl.dsp.layout("movewindowto d"))

hl.bind(mod .. " + SHIFT + Slash", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"))

hl.bind(mod .. " + ALT + L", hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.bind(mod .. " + SHIFT + E", hl.dsp.exit())
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 3"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 3"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("dms ipc call audio micmute"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("dms ipc call brightness increment 5 \"\""), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5 \"\""), { locked = true, repeating = true })

hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mod .. " + SHIFT + T", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + W", hl.dsp.group.toggle())

hl.bind(mod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(mod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + L", hl.dsp.focus({ direction = "right" }))

hl.bind(mod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))
hl.bind(mod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(mod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))

hl.bind("ALT + Tab", hl.dsp.window.cycle_next({ next = true }))
hl.bind("ALT + SHIFT + Tab", hl.dsp.window.cycle_next({ prev = true }))

hl.bind(mod .. " + Home", hl.dsp.focus({ window = "first" }))
hl.bind(mod .. " + End", hl.dsp.focus({ window = "last" }))

hl.bind(mod .. " + CTRL + left", hl.dsp.focus({ monitor = "l" }))
hl.bind(mod .. " + CTRL + right", hl.dsp.focus({ monitor = "r" }))
hl.bind(mod .. " + CTRL + H", hl.dsp.focus({ monitor = "l" }))
hl.bind(mod .. " + CTRL + J", hl.dsp.focus({ monitor = "d" }))
hl.bind(mod .. " + CTRL + K", hl.dsp.focus({ monitor = "u" }))
hl.bind(mod .. " + CTRL + L", hl.dsp.focus({ monitor = "r" }))

hl.bind(mod .. " + SHIFT + CTRL + left", hl.dsp.window.move({ monitor = "l" }))
hl.bind(mod .. " + SHIFT + CTRL + down", hl.dsp.window.move({ monitor = "d" }))
hl.bind(mod .. " + SHIFT + CTRL + up", hl.dsp.window.move({ monitor = "u" }))
hl.bind(mod .. " + SHIFT + CTRL + right", hl.dsp.window.move({ monitor = "r" }))
hl.bind(mod .. " + SHIFT + CTRL + H", hl.dsp.window.move({ monitor = "l" }))
hl.bind(mod .. " + SHIFT + CTRL + J", hl.dsp.window.move({ monitor = "d" }))
hl.bind(mod .. " + SHIFT + CTRL + K", hl.dsp.window.move({ monitor = "u" }))
hl.bind(mod .. " + SHIFT + CTRL + L", hl.dsp.window.move({ monitor = "r" }))

hl.bind(mod .. " + Page_Down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + Page_Up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + U", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + I", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + CTRL + down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mod .. " + CTRL + up", hl.dsp.window.move({ workspace = "e-1" }))
hl.bind(mod .. " + CTRL + U", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mod .. " + CTRL + I", hl.dsp.window.move({ workspace = "e-1" }))

hl.bind(mod .. " + SHIFT + Page_Down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mod .. " + SHIFT + Page_Up", hl.dsp.window.move({ workspace = "e-1" }))
hl.bind(mod .. " + SHIFT + U", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mod .. " + SHIFT + I", hl.dsp.window.move({ workspace = "e-1" }))

hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + CTRL + mouse_down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mod .. " + CTRL + mouse_up", hl.dsp.window.move({ workspace = "e-1" }))

hl.bind(mod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mod .. " + 9", hl.dsp.focus({ workspace = 9 }))

hl.bind(mod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))

hl.bind(mod .. " + bracketleft", hl.dsp.layout("preselect l"))
hl.bind(mod .. " + bracketright", hl.dsp.layout("preselect r"))

hl.bind(mod .. " + R", hl.dsp.layout("togglesplit"))
-- TODO: manual review on line 390 — resizeactive: expected 'X Y' or 'X% Y%', got "100%"
-- hl.bind(mod .. " + CTRL + F", hl.dsp.resizeactive("exact 100%"))

hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { description = "Move window" })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { description = "Resize window" })

hl.bind(mod .. " + code:20", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { description = "Expand window left" })
hl.bind(mod .. " + code:21", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { description = "Shrink window left" })

hl.bind(mod .. " + minus", function() local w = hl.get_active_window(); if not w then return end; hl.dispatch(hl.dsp.window.resize({ x = math.floor(w.size.x * -10 / 100), y = 0, relative = true })) end, { repeating = true })
hl.bind(mod .. " + equal", function() local w = hl.get_active_window(); if not w then return end; hl.dispatch(hl.dsp.window.resize({ x = math.floor(w.size.x * 10 / 100), y = 0, relative = true })) end, { repeating = true })
hl.bind(mod .. " + SHIFT + minus", function() local w = hl.get_active_window(); if not w then return end; hl.dispatch(hl.dsp.window.resize({ x = 0, y = math.floor(w.size.y * -10 / 100), relative = true })) end, { repeating = true })
hl.bind(mod .. " + SHIFT + equal", function() local w = hl.get_active_window(); if not w then return end; hl.dispatch(hl.dsp.window.resize({ x = 0, y = math.floor(w.size.y * 10 / 100), relative = true })) end, { repeating = true })

hl.bind("Print", hl.dsp.exec_cmd("dms screenshot"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("dms screenshot full"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("dms screenshot window"))

-- Source: ./dms/cursor.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("dms.cursor")

-- Source: ./dms/outputs.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("dms.outputs")
-- Source: ./dms/binds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("dms.binds")
hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        numlock_by_default = true,
        sensitivity = 0.2,
        force_no_accel = 0,
        touchpad = {
            natural_scroll = true,
        },
    },
    -- ==================
    -- GENERAL LAYOUT
    -- ==================
    general = {
        gaps_in = 5,
        gaps_out = 5,
        border_size = 0, -- off in niri
        col = {
            active_border = "rgba(707070ff)",
            inactive_border = "rgba(d0d0d0ff)",
        },
        layout = "master",
    },
    cursor = {
        inactive_timeout = 5,
    },
    -- ==================
    -- DECORATION
    -- ==================
    decoration = {
        rounding = 12,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 30,
            render_power = 5,
            offset = "0 5",
            color = "rgba(00000070)",
        },
    },
    -- ==================
    -- ANIMATIONS
    -- ==================
    animations = {
        enabled = true,
    },
    -- ==================
    -- LAYOUTS
    -- ==================
    master = {
        mfact = 0.5,
    },
    -- ==================
    -- MISC
    -- ==================
    misc = {
        on_focus_under_fullscreen = 1,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        vrr = 1,
    },
    -- GESTURE
    -- ==================
    -- WINDOW RULES
    -- ==================
    --
    -- DMS windows floating by default
    -- windowrule {
    --   name = windowrule-1
    --   opacity = 0.9 0.9
    --   match:float = 0
    --   match:focus = 0
    -- }
    --
    -- layerrule {
    --   name = layerrule-1
    --   no_anim = on
    --   match:namespace = ^(quickshell)$
    -- }
    -- ==================
    -- KEYBINDINGS
    -- ==================
    -- === Application Launchers ===
    -- supershortcuts
    -- hyprscrolling keymaps
    -- === Cheat sheet
    -- === Security ===
    -- === Audio Controls ===
    -- === Brightness Controls ===
    -- === Window Management ===
    -- === Focus Navigation ===
    -- === Window Movement ===
    -- windows switcher
    -- === Column Navigation ===
    -- === Monitor Navigation ===
    -- === Move to Monitor ===
    -- === Workspace Navigation ===
    -- === Move Workspaces ===
    -- === Mouse Wheel Navigation ===
    -- === Numbered Workspaces ===
    -- === Move to Numbered Workspaces ===
    -- === Column Management ===
    -- === Sizing & Layout ===
    -- === Move/resize windows with mainMod + LMB/RMB and dragging ===
    -- === Move/resize windows with mainMod + LMB/RMB and dragging ===
    -- === Manual Sizing ===
    -- === Screenshots ===
    -- === System Controls ===
    --bind = $mod SHIFT, P, dpms, off
    -- debug
    debug = {
        disable_logs = true,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("bash -c \"wl-paste --watch cliphist store &\"")
end)

