cursor #e9e1dc
cursor_text_color #d3c4b8

foreground            #e9e1dc
background            #161310
selection_foreground  #3c2e20
selection_background  #d9c2af
url_color             #e9bf97

color0   #161310
color1   #ff7a72
color2   #88e974
color3   #ffe672
color4   #ddad7f
color5   #6b4826
color6   #e9bf97
color7   #f4ede5
color8   #46423d
color9   #ffa49f
color10  #b4ffa5
color11  #ffefa5
color12  #ffd7b2
color13  #ffdec0
color14  #ffead6
color15  #fffbf8
