cursor #e1e4da
cursor_text_color #c3c8bb

foreground            #e1e4da
background            #11140f
selection_foreground  #273421
selection_background  #bccbb0
url_color             #a8d292

color0   #11140f
color1   #e44a69
color2   #88d66e
color3   #dbbb7b
color4   #5e9b3e
color5   #849d77
color6   #a8d292
color7   #abb2bf
color8   #5c6370
color9   #e05f7d
color10  #9ce086
color11  #e8cd97
color12  #b4e19c
color13  #5f8336
color14  #578549
color15  #ffffff
