cursor #e4e3d6
cursor_text_color #c7c7b7

foreground            #e4e3d6
background            #13140d
selection_foreground  #2f321b
selection_background  #c6c9a8
url_color             #c1cd7d

color0   #13140d
color1   #e34a72
color2   #8fd66e
color3   #dbb57b
color4   #89963c
color5   #929969
color6   #c1cd7d
color7   #abb2bf
color8   #5c6370
color9   #e05f85
color10  #a2e086
color11  #e8c897
color12  #d0db8e
color13  #7f7c35
color14  #717f46
color15  #ffffff
